version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: vue-multimodulo-app
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
